# Generated by Django 5.1.7 on 2025-03-22 02:57

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_cv_user_dob_user_education_user_experience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cv",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="cv"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Username must contain only letters, numbers, and underscores",
                        regex="^[a-zA-Z0-9_]+$",
                    )
                ],
            ),
        ),
    ]
