# Generated by Django 5.1.7 on 2025-03-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_cv_alter_user_img_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="keywords",
        ),
    ]
