# Generated by Django 5.1.7 on 2025-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="fail",
            field=models.BooleanField(default=False),
        ),
    ]
