# Generated by Django 5.1.7 on 2025-04-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_application_fail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="hr_time_options",
        ),
        migrations.RemoveField(
            model_name="application",
            name="interview_options_time",
        ),
        migrations.AddField(
            model_name="application",
            name="offer_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="offer_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
