# Generated by Django 5.1.7 on 2025-04-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_remove_application_hr_time_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="ats_res",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
