# Generated by Django 5.1.7 on 2025-05-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_application_created_at_application_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="salary",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
