# Generated by Django 5.1.7 on 2025-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_application_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="insurance",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="termination",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="salary",
            field=models.CharField(blank=True, null=True),
        ),
    ]
