# Generated by Django 5.1.7 on 2025-03-26 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=200)),
                ("answer_q", models.CharField(max_length=200, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("boolean", "boolean"),
                            ("multichoice", "multichoice"),
                        ],
                        default="boolean",
                        max_length=50,
                    ),
                ),
                ("choices", models.JSONField(null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
            ],
        ),
    ]
