# Generated by Django 5.1.7 on 2025-03-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('answer_q', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(choices=[('boolean', 'boolean'), ('text', 'text')], default='boolean', max_length=50)),
            ],
        ),
    ]
