# Generated by Django 5.1.7 on 2025-03-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=200)),
                ("answer", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=50)),
            ],
        ),
    ]
