# Generated by Django 5.1.7 on 2025-04-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
