# Generated by Django 5.1.7 on 2025-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_alter_question_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("boolean", "boolean"),
                    ("multichoice", "multichoice"),
                    ("video", "video"),
                ],
                default="boolean",
                max_length=50,
            ),
        ),
    ]
