# Generated by Django 5.1.7 on 2025-03-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("answer_text", models.TextField()),
                ("result", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
