# Generated by Django 5.1.7 on 2025-03-26 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("answers", "0001_initial"),
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.application",
            ),
        ),
    ]
