# Generated by Django 5.1.7 on 2025-03-28 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
        ("user", "0002_alter_company_managers_alter_jobseeker_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="user.company",
            ),
        ),
    ]
