# Generated by Django 5.1.7 on 2025-04-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_alter_job_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="attend",
            field=models.CharField(default="Remote", max_length=100),
            preserve_default=False,
        ),
    ]
