# Generated by Django 5.1.7 on 2025-04-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_job_attend"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
