# Generated by Django 5.1.7 on 2025-04-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
    ]
