# Generated by Django 5.1.7 on 2025-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_remove_job_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="specialization",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
