# Generated by Django 5.1.7 on 2025-03-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="company",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="jobseeker",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
