# Generated by Django 5.1.8 on 2025-04-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
    ]
