# Generated by Django 5.1.7 on 2025-03-29 00:20

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="company",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="jobseeker",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="company",
            name="est",
        ),
        migrations.RemoveField(
            model_name="company",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="jobseeker",
            name="cv",
        ),
        migrations.RemoveField(
            model_name="jobseeker",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="jobseeker",
            name="education",
        ),
        migrations.RemoveField(
            model_name="jobseeker",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="jobseeker",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="jobseeker",
            name="national_id",
        ),
        migrations.RemoveField(
            model_name="jobseeker",
            name="national_id_img",
        ),
        migrations.RemoveField(
            model_name="jobseeker",
            name="skills",
        ),
        migrations.AddField(
            model_name="user",
            name="cv",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="education",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="est",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="experience",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                unique=True,
                validators=[user.models.validate_egyptian_national_id],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="national_id_img",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("JOBSEEKER", "Jobseeker"), ("COMPANY", "Company")],
                default="JOBSEEKER",
                max_length=20,
            ),
        ),
    ]
