# Generated by Django 5.1.7 on 2025-03-29 00:23

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_company_managers_alter_jobseeker_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="company",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="jobseeker",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
