# Generated by Django 5.1.8 on 2025-04-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_digit",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verify_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
