# Generated by Django 5.1.7 on 2025-04-01 11:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_delete_company_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cv",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="cv"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="img",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
