# Generated by Django 5.1.7 on 2025-04-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_national_id_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="keywords",
        ),
    ]
