# Generated by Django 5.1.7 on 2025-04-02 11:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_user_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
