# Generated by Django 5.1.7 on 2025-04-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_id"),
        ("user", "0008_user_logo"),
    ]

    operations = []
