# Generated by Django 5.1.7 on 2025-04-13 14:55

import django.core.validators
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_user_keywords_user_otp_digit_user_verify_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Itian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Enter a valid email address"
                            )
                        ],
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        validators=[user.models.validate_egyptian_national_id],
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
