# Generated by Django 5.1.7 on 2025-04-13 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_itian"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itian",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Enter a valid email address"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="itian",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
