# Generated by Django 5.1.7 on 2025-04-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_itian_email_alter_itian_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itian",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
