# Generated by Django 5.1.8 on 2025-04-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_itian_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="logo",
        ),
        migrations.AddField(
            model_name="user",
            name="accounts",
            field=models.JSONField(default=dict),
        ),
    ]
