# Generated by Django 5.1.7 on 2025-04-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_itian_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="logo",
        ),
    ]
