# Generated by Django 5.1.7 on 2025-04-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_remove_user_logo_user_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("JOBSEEKER", "Jobseeker"),
                    ("COMPANY", "Company"),
                    ("ADMIN", "Admin"),
                ],
                default="JOBSEEKER",
                max_length=20,
            ),
        ),
    ]
