# Generated by Django 5.1.8 on 2025-04-20 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_user_is_verified_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters and at least 3 characters",
                        regex="^[a-zA-Z ]{3,}$",
                    )
                ],
            ),
        ),
    ]
