# Generated by Django 5.1.8 on 2025-04-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_user_otp_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
