# Generated by Django 5.1.8 on 2025-04-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_requests",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
