# Generated by Django 5.1.7 on 2025-04-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_userquestions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquestions",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
