# Generated by Django 5.1.7 on 2025-04-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_user_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="education",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="experience",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="skills",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
