# Generated by Django 5.1.7 on 2025-04-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_alter_user_education_alter_user_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="seniority",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
