# Generated by Django 5.1.7 on 2025-04-30 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_alter_user_education_alter_user_experience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
