# Generated by Django 5.1.7 on 2025-05-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0025_alter_user_otp_created_at"),
        ("user", "0025_user_seniority"),
    ]

    operations = []
