# Generated by Django 5.1.7 on 2025-05-05 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0027_alter_user_managers_alter_user_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters and at least 3 characters",
                        regex="^[a-zA-Z ]{3,}$",
                    )
                ],
            ),
        ),
    ]
