# Generated by Django 5.1.7 on 2025-05-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0027_branch_track_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="graduation_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
