# Generated by Django 5.1.7 on 2025-05-05 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0028_alter_track_graduation_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="track",
        ),
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.branch",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.track",
            ),
        ),
    ]
