# Generated by Django 5.1.7 on 2025-05-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0030_remove_track_graduation_year_user_graduation_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="graduation_year",
            new_name="iti_grad_year",
        ),
    ]
