# Generated by Django 5.1.7 on 2025-05-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0027_alter_user_managers_user_summary"),
        ("user", "0028_alter_user_name"),
        ("user", "0031_rename_graduation_year_user_iti_grad_year"),
    ]

    operations = []
